version: '3.6'

services:
  # Backend API
  mope-api:
    container_name: backend
    build: ./
    command: yarn start
    working_dir: /STUDY/containers/mope-api
    environment:
      POSTGRES_URI: postgres:secret//gulbadam:secret@postgres:5432/mope-db
      REDIS_URI: redis://redis:6379
    ports:
      - "3001:3001"
    volumes:
      - ./:/STUDY/containers/mope-api
# Postgress

  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: gulbadam
      POSTGRES_PASSWORD: secret
      POSTGRES_URL: postgres://gulbadam:secret@localhost:5432/mope-db
      POSTGRES_DB: mope-db
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
      # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

    
